// <auto-generated />
using System;
using GrowMate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrowMate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrowMate.Domain.GardenBeds.GardenBed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название грядки");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Тип грядки");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasComment("Идентификатор пользователя-владельца");

                    b.HasKey("Id");

                    b.ToTable("GardenBeds", (string)null);
                });

            modelBuilder.Entity("GrowMate.Domain.GardenTasks.GardenTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Срок выполнения");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Выполнено");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор растения");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Задача");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Тип задачи");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("IsCompleted", "DueDate");

                    b.ToTable("GardenTasks", (string)null);
                });

            modelBuilder.Entity("GrowMate.Domain.Plants.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Описание / Заметки");

                    b.Property<int>("GardenBedId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор грядки");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название растения");

                    b.Property<int?>("PlantTemplateId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор шаблона культуры");

                    b.Property<DateTime>("PlantingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Дата посадки");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Тип растения");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Variety")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Сорт");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("PlantTemplateId");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("GrowMate.Domain.Plants.PlantTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Описание культуры");

                    b.Property<int?>("FirstFertilizingAfterDays")
                        .HasColumnType("integer")
                        .HasComment("Через сколько дней после посадки рекомендована первая подкормка");

                    b.Property<int?>("FirstTreatmentAfterDays")
                        .HasColumnType("integer")
                        .HasComment("Через сколько дней после посадки рекомендована первая обработка");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название культуры (шаблон)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Тип культуры");

                    b.Property<int?>("WateringIntervalDays")
                        .HasColumnType("integer")
                        .HasComment("Рекомендуемый интервал полива в днях");

                    b.HasKey("Id");

                    b.ToTable("PlantTemplates", (string)null);
                });

            modelBuilder.Entity("GrowMate.Domain.GardenTasks.GardenTask", b =>
                {
                    b.HasOne("GrowMate.Domain.Plants.Plant", "Plant")
                        .WithMany("Tasks")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GrowMate.Domain.Plants.Plant", b =>
                {
                    b.HasOne("GrowMate.Domain.GardenBeds.GardenBed", "GardenBed")
                        .WithMany("Plants")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrowMate.Domain.Plants.PlantTemplate", "Template")
                        .WithMany("Plants")
                        .HasForeignKey("PlantTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GardenBed");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GrowMate.Domain.GardenBeds.GardenBed", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GrowMate.Domain.Plants.Plant", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GrowMate.Domain.Plants.PlantTemplate", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
